# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [27]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [28]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

### Step 3. Assign it to a variable called chipo.

In [29]:
chipo = pd.read_csv(url, sep='\t')

In [26]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [30]:
chipo['item_price'] = chipo['item_price'].str.replace('$', '', regex=False).astype(float)

### Step 4. How many products cost more than $10.00?

In [33]:
products = chipo[chipo['quantity'] == 1][['item_name', 'choice_description', 'item_price']].drop_duplicates()
products_over_10 = products[products['item_price'] > 10]
print(products_over_10.shape[0])

685

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [34]:
products = chipo[chipo['quantity'] == 1][['item_name', 'choice_description', 'item_price']].drop_duplicates()
products.sort_values(by='item_price', ascending=True)

,item_name,choice_description,item_price
53,Canned Soda,[Sprite],1.09
126,Canned Soda,[Coca Cola],1.09
117,Canned Soda,[Diet Dr. Pepper],1.09
28,Canned Soda,[Dr. Pepper],1.09
228,Canned Soda,[Mountain Dew],1.09
...,...,...,...
2804,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",11.89
4313,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
1159,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89
1132,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.89
2740,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.89

### Step 6. Sort by the name of the item

In [35]:
products.sort_values(by='item_name', ascending=True)

,item_name,choice_description,item_price
357,6 Pack Soft Drink,[Coke],6.49
341,6 Pack Soft Drink,[Diet Coke],6.49
298,6 Pack Soft Drink,[Sprite],6.49
721,6 Pack Soft Drink,[Nestea],6.49
3141,6 Pack Soft Drink,[Lemonade],6.49
...,...,...,...
2384,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
1395,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49
2851,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25

### Step 7. What was the quantity of the most expensive item ordered?

In [36]:
most_expensive = chipo.sort_values(by='item_price', ascending=False).head(1)
print(most_expensive[['item_name', 'choice_description', 'quantity', 'item_price']])

                         item_name choice_description  quantity  item_price
3598  Chips and Fresh Tomato Salsa                NaN        15       44.25

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [37]:
veggie_salad_bowl_orders = chipo[chipo['item_name'] == 'Veggie Salad Bowl'].shape[0]
print(veggie_salad_bowl_orders)

18

### Step 9. How many times did someone order more than one Canned Soda?

In [38]:
more_than_one_canned_soda = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].shape[0]
print(more_than_one_canned_soda)

20